### PR TITLE
fix(workflow-test*): Update the number of concurrent jobs

### PR DESCRIPTION
**Pull request by jchauncey**
Creates 3 new default values:
maxWorkflowReleaseConcurrentBuilds = 1
maxWorkflowTestConcurrentBuilds = 1
maxWorkflowTestPRConcurrentBuilds = 4

### CODE REVIEW

**Comment by mboersma** [comment]
Looks straightforward. What were the previous limits for these job types? And is this a Jenkins-wide cap, or per-node?

**Comment by jchauncey** [comment]
this is per job. and only for e2e tests (workflow-test\* jobs). Originally we could run 6 concurrent jobs (1 on each node) now we are bound by the number of leasable clusters we have available.

**Comment by sgoings** [comment]
Removing 2.0-rc2 milestone assignment as a way to keep our rc2 milestone clean and customer deliverable focused: https://github.com/pulls?utf8=%E2%9C%93&q=user%3Adeis+milestone%3Av2.0-rc2+

**Comment by jchauncey** [comment]
do we really want to do that? Shouldnt we track work completed via the milestones? Regardless of repo?

**Pull request merged**
