### PR TITLE
feat(workflow_test): add author name to slack notification

### PR DESCRIPTION
**Pull request by vdice**
Closes https://github.com/deis/jenkins-jobs/issues/162

### CODE REVIEW

**Comment by vdice** [comment]
@jchauncey let me know your thoughts on this and/or if there might be a more effective way of raising alert to the master commit author if e2e fails...

**Comment by jchauncey** [comment]
love this idea

**Comment by vdice** [comment]
Test of this resulted in:

```
jenkins BOT [4:53 PM]  
----------------
workflow-test - #990 Failure after 21 min (Open)
Test Status:
    Passed: 270, Failed: 1, Skipped: 35
Commit Author: Jenkins User
Test Report: https://ci.deis.io/job/workflow-test/990/testReport
Upstream job: https://ci.deis.io/job/workflow-e2e/70/


[4:53]  
----------------
No Changes.
```

The original workflow-e2e build job was triggered manually... that may play a part... otherwise would hope not to see `Jenkins User`

**Comment by vdice** [comment]
This is going to need more attention; removed the LGTMs and put back 'in progress'...

**Comment by vdice** [comment]
This should be good now; author name coming through via test job https://ci.deis.io/job/workflow-e2e-pr-clone/ws/env.properties/*view*/

**Comment by vdice** [comment]
ping @jchauncey @Joshua-Anderson

**Pull request merged**
