### PR TITLE
feat(component_release.groovy): add <component>-release job

### LINKED ISSUE #110: create component release job
We have the need for a `component-release-job` that would track git push events to a `release*` branch on any/all of our Workflow component [repos](https://github.com/deis/jenkins-jobs/blob/master/common.groovy#L1-L17).

Use case: If someone creates a release branch, we want a Docker image created and pushed from that release branch. 

Further, if they modify that branch (i.e. from fixes, cherry-picking or rebase), this job should fire again and push a new image, ready for use in a release chart.
#### Implementation details:

As of this writing, we are leaning to one `.groovy` file set up to track all component repos, rather than adding separate `-release` jobs for each component via additional configuration in the existing `component_jobs.groovy` [file](https://github.com/deis/jenkins-jobs/blob/master/jobs/component_jobs.groovy).

### PR DESCRIPTION
**Pull request by vdice**
For all Workflow component repos, to watch for a commit on a given release branch,
specified via the RELEASE parameter.

Live example built from DSL on this branch: https://ci.deis.io/job/dockerbuilder-release/1/console

TODO
- [x] mark this as completed in https://github.com/deis/deisrel/issues/100 if/when merged
- [x] delete manually created `component-seed-job`

Closes #110 
Ref https://github.com/deis/workflow/pull/362

### CODE REVIEW

**Comment by vdice** [comment]
the only weirdness is w/ this DSL _any_ commit to the repo (say, master commit) triggers this job (though it does checkout the release branch and just build/deploy from the HEAD commit), for instance here is an example: https://ci.deis.io/job/controller-release/1/console

Could try adding `refspec('+refs/heads/release-${RELEASE}:refs/remotes/origin/release-${RELEASE}')` to the `git` block... not sure if that would change the behavior or not

Edit: it does not.  a githubPush event to the repo, regardless of branch on `origin`, will kick this off -- and though its inefficient and wastes a cycle on a node, it only _re-deploys_ from existing `HEAD` commit on the release branch, which I don't believe should be an issue unless I'm missing something...

**Comment by vdice** [comment]
@krancour updated with your good idea of just checking if `GIT_BRANCH` matches `release-${RELEASE}`.  If yes, proceed; if no, simply exit 0.

**Comment by vdice** [comment]
@krancour I also updated the `RELEASE` value to the next anticipated release, `v2.2.0`.  While no `release-v2.2.0` branch exists on any of the components, once they are created, these jobs will "just work".

Please review when convenient.

**Comment by bacongobbler** [comment]
should we add some documentation in the release docs that explains what this release job will do? :)

**Comment by vdice** [comment]
@bacongobbler definitely -- good call.  Will create the PR and ref it here asap.

**Comment by vdice** [comment]
@bacongobbler docs PR added: https://github.com/deis/workflow/pull/362

**Pull request merged**
