### PR TITLE
feat(*): add monitor support for promotion and release

### PR DESCRIPTION
**Pull request by vdice**
Closes https://github.com/deis/jenkins-jobs/issues/175
Closes https://github.com/deis/jenkins-jobs/issues/201

TODO
- [x] remove the following deprecated jobs:
  - https://ci.deis.io/job/grafana/
  - https://ci.deis.io/job/grafana-pr/
  - https://ci.deis.io/job/influxdb/
  - https://ci.deis.io/job/influxdb-pr/
  - https://ci.deis.io/job/telegraf/
  - https://ci.deis.io/job/telegraf-pr/

cc @jchauncey

### CODE REVIEW

**Comment by vdice** [comment]
I still need to manually test these via a seed job in Jenkins and running some pipelines...

**Comment by vdice** [comment]
Successful component-promote job for monitor: https://ci.deis.io/job/component-promote/212/

Successful monitor release pipeline: https://ci.deis.io/job/release-candidate-promote/25/console

**Comment by krancour** [comment]
After review and some offline discussion, @vdice and I have agreed that with a little bit of refactoring, this PR can satisfy #201, eliminate much special-casing for the monitor repo, and be easier to comprehend and review as a result.

**Comment by vdice** [comment]
@krancour @jchauncey this is back up for review.  As @krancour [noted](https://github.com/deis/jenkins-jobs/pull/200#issuecomment-239311856), we decided to feed a few birds with one worm (see what I did there?) and get the work out of the way in this change to enable support for repos housing multiple components (like monitor).  

Not only that, @krancour had invaluable feedback on the job and shell scripting structure that exists now in this repo, including supplying a great approach to making the groovy to bash connection much more dynamic/communicative, whereas previously it was quite static and fragile.  

To that end, I've only updated logic particular to the needs of this PR, but I am eager to employ the new patterns (see [here](https://github.com/vdice/jenkins-jobs/blob/3f1b0cd55fae0554f000982f6e30d8ab9cf4aff6/jobs/component_release.groovy#L56-L69) for an example) in follow-up refactor tickets.

Regarding the latest code here, both single-component and multi-component build/promote pipelines and release pipelines have been tested.  Please see:

https://ci.deis.io/job/monitor/2/
https://ci.deis.io/job/slugbuilder/40

https://ci.deis.io/job/monitor-release/21/
https://ci.deis.io/job/slugbuilder-release/7

**Pull request merged**
