### PR TITLE
ref(helm_chart_actions.sh): add timestamp to pr charts

### PR DESCRIPTION
**Pull request by vdice**
requires https://github.com/deis/jenkins-jobs/pull/304

TODO
 - [ ] test relevant chart pr pipeline to make sure :)

### CODE REVIEW

**Comment by kmala** [comment]
doesn't this require canary of helm as https://github.com/kubernetes/helm/pull/1675 is not released and you have another pr to update the helm version

**Comment by vdice** [comment]
@kmala it looks like the change you mentioned (that we need here) was released in v2.1.0: https://github.com/kubernetes/helm/releases/tag/v2.1.0

**Comment by kmala** [comment]
Weird the PR isn't tagged. LGTM2 then.

**Comment by vdice** [comment]
@kmala yea, that is odd.  I'll be sure to test this on Jenkins before merging...

**Pull request merged**
