### PR TITLE
fix(monitor): Just remove inclusion check altogether

### PR DESCRIPTION
**Pull request by jchauncey**

### CODE REVIEW

**Comment by jchauncey** [comment]
fixes #80

**Comment by bacongobbler** [comment]
Is there a reason that this was originally needed? I was trying to hack up a PR to make it work, but if there's no need for this then we can merge, but I'd be happy to take the time and find a fix.

**Comment by jchauncey** [comment]
Yes the monitoring repo contains 3 sub dirs and I would rather do an inclusion check to see which one to build. Right now this doesnt work with the github pr builder but figured the master jobs could continue to use it. Instead, we will just build all 3 on new master run

**Comment by bacongobbler** [comment]
Excellent. [The job's green again](https://ci.deis.io/job/component-seed-job/57/console). Thank you!

**Pull request merged**
