### PR TITLE
feat(jobs): set slack defaults in each project

### PR DESCRIPTION
**Pull request by vdice**

### CODE REVIEW

**Comment by jchauncey** [comment]
🚢

**Comment by vdice** [comment]
@Joshua-Anderson good question. I've read up on the [Jenkins Slack Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Slack+Plugin) and around Slack integrations, but I can't seem to figure out if that token should necessarily be secret.  (It's just a plaintext/non-hidden field in the setup for the plugin in Jenkins.)  

Were there security implications you were specifically aware of?  If so, will definitely want to revisit and obfuscate/encrypt if possible (though aforementioned plugin doesn't seem to offer explicit support.)

**Comment by Joshua-Anderson** [comment]
The slack integration token is authentication for the slack api. This token would allow people to completely control the bot, so they would get read and write access to your slack chat.

**Comment by Joshua-Anderson** [comment]
I would highly recommended revoking the token ASAP.

**Comment by vdice** [comment]
Thanks @Joshua-Anderson.  Token regenerated.

**Pull request merged**
